Add support for <sub-title> (episode name) XMLTV tags
kodi-pvr/pvr.iptvsimple pull request #151
Opened 2017-08-13 08:33 UTC by Jalle19

Closes #91

@excorp can you try this?

2017-08-22 06:47 UTC, Jalle19 commented
ping @excorp

2018-03-01 11:03 UTC, shaneypoopers commented
Did this get approved yet? I don't see it in the main branch?

2019-01-10 02:05 UTC, kyl416 commented
Any update on getting this approved?

2019-02-07 08:04 UTC, afedchin requested changes
please drop unrelated changes.

2019-02-07 08:04 UTC, afedchin commented on src/PVRIptvData.cpp
> -void PVRIptvData::ReaplyChannelsLogos(const char * strNewPath)
how this removal related to PR changes?

2019-08-19 22:09 UTC, phunkyfish commented
Closing as superseded by #261 and #263

2019-08-19 22:09 UTC, closed without merging