Urlencode & append extension to channel logo set from channel name for remote path logo source
kodi-pvr/pvr.iptvsimple pull request #211
Opened 2018-12-23 08:58 UTC by allixx

https://github.com/kodi-pvr/pvr.iptvsimple/issues/210

2018-12-23 09:18 UTC, afedchin requested changes

2018-12-23 09:18 UTC, afedchin commented on src/client.h
> +extern const std::string UrlEncode(const std::string &value);
you can declare `UrlEncode` method where it's used i.e. in `PVRIptvData.cpp` file. no need to export it

2018-12-23 10:33 UTC, allixx commented
I'm not sure what jenkins problem actually is.

2018-12-23 12:18 UTC, afedchin commented
jenkins build this please

2019-04-15 07:07 UTC, afedchin requested changes

2019-04-15 07:07 UTC, afedchin commented on src/PVRIptvData.cpp
> +static const std::string UrlEncode(const std::string &value) {
please change your code style according to the guidelines https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#31-braces

2019-08-13 01:25 UTC, phunkyfish commented on src/PVRIptvData.cpp
> +  for (std::string::const_iterator i = value.begin(), n = value.end(); i != n; ++i)
Why not: ```for (auto c : value)``` and remove ```std::string::value_type c = (*i);``` completely?

2019-08-13 01:25 UTC, phunkyfish commented on src/PVRIptvData.cpp
> +          tmpChannel.strTvgLogo = \
Just put this on one line

2019-08-13 01:25 UTC, phunkyfish commented on src/PVRIptvData.h
> +#include <sstream>
I think can be removed

2019-08-13 01:25 UTC, phunkyfish commented on src/PVRIptvData.h
> +#include <iomanip>
Should be in cpp file and not the header.

2019-08-27 15:02 UTC, phunkyfish commented
@allixx are you still interested in finishing this PR?

2019-08-27 16:47 UTC, allixx commented
Sorry. 
Looks like thanks to your impressive refactor work all required bits are already there, and all that's left is to add the urlencode function (could it somehow be pulled from kodi api by the way?) and url formatting conditional statement in playlist loader's channel parser, right?

2019-08-27 16:53 UTC, phunkyfish commented
So this would need to be done in the Leia branch as that was not refactored.

And then again in the Matrix branch. Or you could just do it in Matrix. Up to you.

2019-08-27 17:09 UTC, allixx commented
I seem to remember kso saying they didn't want any new features in Leia, so this probably goes to Matrix.
Can you do all the required changes by yourself, if you are up to it of course, it's going to be much quicker and I don't want to waste any more of your time reviewing my mistakes.

2019-08-27 17:26 UTC, phunkyfish commented
Sure, no problem. If you can test it in Matrix I will add to next PR?

2019-08-27 18:19 UTC, allixx commented
Yes, I can help with testing I guess. Cannot promise instant reaction time though...

2019-08-27 18:19 UTC, closed without merging

2019-08-27 19:13 UTC, phunkyfish commented
No rush.