[Matrix] API update / compile warning fix
kodi-pvr/pvr.iptvsimple pull request #406
Opened 2020-07-16 10:02 UTC by AlwinEsch

API related to xbmc/xbmc#17438 (DEMUX_PACKET not used there)

2020-07-16 18:54 UTC, phunkyfish commented
Why have an attribute hidden in all
classes if they are namespaced?

2020-07-16 19:26 UTC, AlwinEsch commented
Was come to my mind that if another place can find it, that it must also be somewhere in code and memory listed, if now every part add it to somewhere, comes a really big list :thinking: 

Also seen some compile warnings during build.

2020-08-09 19:43 UTC, AlwinEsch commented
Has removed this first commit about attribute hidden and pushed to check travis build about

2020-08-10 11:24 UTC, phunkyfish commented
Remind me again why the bump to 7.0.0 is needed?

2020-08-11 23:24 UTC, AlwinEsch commented
> Remind me again why the bump to 7.0.0 is needed?

Is about the inputstream API where used inside PVR. By inputstream is to have them correct in "C" and few memleaks fixed there.
Problem is only that PVR has this stream parts also in use and need increase too.

WIth major increase is related to @ksooo (and he arranged by Team) where want it by API change.

2020-08-12 06:34 UTC, phunkyfish commented
Ok, that’s good with me.

2020-08-12 06:35 UTC, phunkyfish requested changes

2020-08-12 06:35 UTC, phunkyfish commented on pvr.iptvsimple/addon.xml.in
> +- Fixed: Prevent some compile warnings by add of ATTRIBUTE_HIDDEN
Like should be removed

2020-08-12 06:35 UTC, phunkyfish commented on pvr.iptvsimple/changelog.txt
> +- Fixed: Prevent some compile warnings by add of ATTRIBUTE_HIDDEN
Line should be removed.

2020-10-30 16:29 UTC, phunkyfish approved these changes

2020-10-31 10:14 UTC, merged