Catchup duration keyword
kodi-pvr/pvr.iptvsimple pull request #614
Opened 2022-07-19 11:47 UTC by dcesari

The catchup string from my itpv provider looks like `http://example.com/channelname/video-${start}-${duration}.m3u8?token=xxxxxx` so I get a wrong address `http://example.com/channelname/video-1658199600-$15600.m3u8?token=xxxxxx` (with a redundant `$`), the proposed change should take into account this situation while not breaking the case in which only the `{duration}` keyword without `$` is used, which, as far as I understand, is a possible case as well.

2022-07-19 12:51 UTC, phunkyfish commented
The change looks fine to me. However the same change will need to be made to `inputstream.ffmpegdirect`, it shares much of the same code as it generates the URLs in a similar fashion. Please update the `README.md` with the new specifier in this add-on.

Also, remember you need to add an entry to the `changelog.txt` and the `addon.xml.in` when you update a binary add-on. Then it’s easy to release it.

2022-07-21 09:24 UTC, dcesari commented
I documented the change and shortened the first commit comment; do I understand correctly that you were asking me to add a new version for this change? If it is good, I will do the same for inputstream.ffmpegdirect.
Many thanks.

2022-07-21 09:40 UTC, phunkyfish requested changes
Nearly there. Just a few minor changes needed.

You won’t need the readme change in ffmpegdirect, but the other changes will be required.

2022-07-21 09:40 UTC, phunkyfish commented on README.md
> +- `${duration}`: Same as above with a different syntax
Should read: “Same as `{duration}`.”

If you use phrases such as, same as above and the line is moved it loses context.

2022-07-21 09:40 UTC, phunkyfish commented on pvr.iptvsimple/addon.xml.in
> +  version="20.3.2"
As you are adding functionality the minor version should be increased. So it should be `20.4.0`.

2022-07-21 09:40 UTC, phunkyfish commented on pvr.iptvsimple/changelog.txt
> +v20.3.2
As you are adding functionality the minor version should be increased. So it should be `20.4.0`.

2022-07-21 10:31 UTC, phunkyfish commented
Ok, now you just want to tidy up the last few commits? Do you know how to do that?

Easiest way is to undo the last 3 commits and then recreate them. One for readme update and one for the verison.

To undo the last 3 commits on the command line: `git reset HEAD~3`

Then it’s just adding the files to each commit. When you push it back up you’ll need to add the force flag `-ff` to your `git push` command.

2022-07-22 09:12 UTC, merged

2022-07-22 09:13 UTC, phunkyfish commented
Thanks for the contribution!